### ISSUE TITLE
Test Case DOES NOT PASS

### ISSUE THREAD

**Issue by timchunght** [steve228uk/Downpour#3]
The following test case does not pass
```
func xtestStandardShow4() {
        let downpour = Downpour(string: "Show.1.0.Name.S01.E03.My.Ep.Name-Group")
        XCTAssertEqual(downpour.title, "Show 1.0 Name")
        XCTAssertEqual(downpour.season, "01")
        XCTAssertEqual(downpour.episode, "03")
        XCTAssertEqual(downpour.type, .some(.tv))
        XCTAssertNil(downpour.year)
    }
```

I tested the code also and the returned title is`Show 1 0 Name S01 E03 My Ep Name-Group` and NOT `Show 1.0 Name`

**Comment by Ponyboy47** [comment]
This is because of the string cleaning that happens to replace characters like a . with spaces. This test will always fail because how can we distinguish between a . that should be converted to a space and one that shouldn't?

I'm working on and actively using my fork of Downpour which is working with the latest swift (3.1) and works on linux. I've tried solving the problem with the specific test you're mentioning and you're more than welcome to check out and use my fork until the repo owner accepts my pull request :)

**Comment by steve228uk** [comment]
@Ponyboy47 Sorry for the delay, merged this. I'm happy to provide you contributor access to the repo if you'd like to continue submitting changes without delay.

I can't think of a way to detect this unfortunately but it doesn't affect my use case as the TMDB API we use for @TryFetch ignored periods anyway.

**Comment by Ponyboy47** [comment]
@steve228uk if you want to make me a contributor that would be excellent! I'll still do most of the dev on my fork, but then I could automatically merge my pull requests. I just got the travis build to succeed on my fork and will be making another pull request shortly :)

All the tests pass and it builds on both Linux and macOS with the latest swift

**Comment by Ponyboy47** [comment]
With the changes from PR #2, all tests should pass now.
